### ISSUE TITLE
Crash when quickly starting then stopping 2000 rules

### ISSUE THREAD

**Issue by pegasign** [elixsr/FwdPortForwardingApp#5]
```java
07-18 23:58:03.815 27697-28123/? I/ForwardingService: Found the relevant Interface. Will attempt to fetch IP Address
07-18 23:58:03.825 27697-27697/? I/MainActivity: Forwarding Enabled: true
07-18 23:58:03.827 27697-28126/? I/TcpForwarder: TCP Thread interrupted, will perform cleanup
07-18 23:58:03.828 27697-28151/? I/TcpForwarder: TCP Thread interrupted, will perform cleanup
07-18 23:58:03.829 27697-28135/? I/TcpForwarder: TCP Thread interrupted, will perform cleanup
07-18 23:58:03.829 27697-28146/? I/TcpForwarder: TCP Thread interrupted, will perform cleanup
07-18 23:58:03.829 27697-28132/? I/TcpForwarder: TCP Thread interrupted, will perform cleanup
07-18 23:58:03.830 27697-28140/? I/TcpForwarder: TCP Thread interrupted, will perform cleanup
07-18 23:58:03.830 27697-28128/? I/TcpForwarder: TCP Thread interrupted, will perform cleanup
07-18 23:58:03.830 27697-28142/? I/TcpForwarder: TCP Thread interrupted, will perform cleanup
07-18 23:58:03.830 27697-28150/? I/TcpForwarder: TCP Thread interrupted, will perform cleanup
07-18 23:58:03.831 27697-28141/? I/TcpForwarder: TCP Thread interrupted, will perform cleanup
07-18 23:58:03.832 27697-28145/? I/TcpForwarder: TCP Thread interrupted, will perform cleanup
07-18 23:58:03.832 27697-28123/? D/ForwardingService: dummy0 vs lo
07-18 23:58:03.832 27697-28123/? D/ForwardingService: p2p0 vs lo
07-18 23:58:03.833 27697-28123/? D/ForwardingService: usb0 vs lo
07-18 23:58:03.833 27697-28123/? D/ForwardingService: sit0 vs lo
07-18 23:58:03.833 27697-28123/? D/ForwardingService: lo vs lo
07-18 23:58:03.833 27697-28123/? I/ForwardingService: Found the relevant Interface. Will attempt to fetch IP Address
07-18 23:58:03.833 27697-28137/? I/TcpForwarder: TCP Thread interrupted, will perform cleanup
07-18 23:58:03.834 27697-28133/? I/TcpForwarder: TCP Thread interrupted, will perform cleanup
07-18 23:58:03.834 27697-28153/? I/TcpForwarder: TCP Thread interrupted, will perform cleanup
07-18 23:58:03.835 27697-28130/? I/TcpForwarder: TCP Thread interrupted, will perform cleanup
07-18 23:58:03.835 27697-28154/? I/TcpForwarder: TCP Thread interrupted, will perform cleanup
07-18 23:58:03.836 27697-28124/? I/TcpForwarder: TCP Thread interrupted, will perform cleanup
07-18 23:58:03.836 285-625/? D/audio_hw_primary: out_set_parameters: enter: usecase(1: low-latency-playback) kvpairs: routing=2
07-18 23:58:03.836 285-625/? V/msm8916_platform: platform_get_output_snd_device: enter: output devices(0x2)
07-18 23:58:03.836 285-625/? V/msm8916_platform: platform_get_output_snd_device: exit: snd_device(speaker)
07-18 23:58:03.836 27697-28152/? I/TcpForwarder: TCP Thread interrupted, will perform cleanup
07-18 23:58:03.836 27697-28139/? I/TcpForwarder: TCP Thread interrupted, will perform cleanup
07-18 23:58:03.837 27697-28131/? I/TcpForwarder: TCP Thread interrupted, will perform cleanup
07-18 23:58:03.837 27697-28143/? I/TcpForwarder: TCP Thread interrupted, will perform cleanup
07-18 23:58:03.837 27697-28147/? I/TcpForwarder: TCP Thread interrupted, will perform cleanup
07-18 23:58:03.837 27697-28134/? I/TcpForwarder: TCP Thread interrupted, will perform cleanup
07-18 23:58:03.838 27697-28129/? I/TcpForwarder: TCP Thread interrupted, will perform cleanup
07-18 23:58:03.838 27697-28149/? I/TcpForwarder: TCP Thread interrupted, will perform cleanup
07-18 23:58:03.838 27697-28138/? I/TcpForwarder: TCP Thread interrupted, will perform cleanup
07-18 23:58:03.838 27697-28136/? I/TcpForwarder: TCP Thread interrupted, will perform cleanup
07-18 23:58:03.838 27697-28148/? I/TcpForwarder: TCP Thread interrupted, will perform cleanup
07-18 23:58:03.839 27697-28127/? I/TcpForwarder: TCP Thread interrupted, will perform cleanup
07-18 23:58:03.839 27697-28125/? I/TcpForwarder: TCP Thread interrupted, will perform cleanup
07-18 23:58:03.847 27697-27697/? I/ForwardingService: Ended the ForwardingService. Cleanup finished.
07-18 23:58:03.858 27697-27697/? I/MainActivity: Response from ForwardingService, Forwarding status has changed.
07-18 23:58:03.860 27697-27697/? I/MainActivity: Forwarding status has changed to false
07-18 23:58:03.884 27697-28123/? E/AndroidRuntime: FATAL EXCEPTION: IntentService[ForwardingService]
                                                   Process: com.elixsr.portforwarder, PID: 27697
                                                   java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ExecutorCompletionService$QueueingFuture@53a4c74 rejected from java.util.concurrent.ThreadPoolExecutor@2d6159d[Terminated, pool size = 17, active threads = 0, queued tasks = 0, completed tasks = 30]
                                                       at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2014)
                                                       at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:794)
                                                       at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1340)
                                                       at java.util.concurrent.ExecutorCompletionService.submit(ExecutorCompletionService.java:152)
                                                       at com.elixsr.portforwarder.forwarding.ForwardingService.onHandleIntent(ForwardingService.java:198)
                                                       at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.os.HandlerThread.run(HandlerThread.java:61)
07-18 23:58:03.888 2216-4073/? W/ActivityManager:   Force finishing activity com.elixsr.portforwarder/.ui.MainActivity
07-18 23:58:03.889 2216-4073/? I/ActivityManager: moveHomeStack, setupComplete:true
07-18 23:58:04.027 2216-3295/? I/OpenGLRenderer: Initialized EGL, version 1.4```

**Comment by pegasign** [comment]
[screencapture-1500418183058.mp4.zip](https://github.com/elixsr/FwdPortForwardingApp/files/1157520/screencapture-1500418183058.mp4.zip)
